export const usuarios = [
    {
        nombre: "Juan Perez",
        numero: "1234567890",
        correo: "juan.perez@example.com",
        faena: "Zaldivar",
        rol: "Administrador",
    },
    {
        nombre: "Maria Lopez",
        numero: "0987654321",
        correo: "maria.lopez@example.com",
        faena: "Zaldivar",
        rol: "Planificador",
    },
    {
        nombre: "Carlos Gomez",
        numero: "1122334455",
        correo: "carlos.gomez@example.com",
        faena: "Zaldivar",
        rol: "Supervisor",
    },
    {
        nombre: "Ana Martinez",
        numero: "5566778899",
        correo: "ana.martinez@example.com",
        faena: "Zaldivar",
        rol: "Operador",
    },
    {
        nombre: "Luis Torres",
        numero: "6677889900",
        correo: "luis.torres@example.com",
        faena: "Zaldivar",
        rol: "Mecánico",
    },
    {
        nombre: "Sofia Ramirez",
        numero: "7788990011",
        correo: "sofia.ramirez@example.com",
        faena: "Zaldivar",
        rol: "Ingeniero",
    },
    {
        nombre: "Pedro Sanchez",
        numero: "8899001122",
        correo: "pedro.sanchez@example.com",
        faena: "Zaldivar",
        rol: "Técnico",
    },
    {
        nombre: "Laura Diaz",
        numero: "9900112233",
        correo: "laura.diaz@example.com",
        faena: "Zaldivar",
        rol: "Supervisor",
    },
    {
        nombre: "Jorge Herrera",
        numero: "1011121314",
        correo: "jorge.herrera@example.com",
        faena: "Zaldivar",
        rol: "Operador",
    },
    {
        nombre: "Elena Vega",
        numero: "1213141516",
        correo: "elena.vega@example.com",
        faena: "Zaldivar",
        rol: "Planificador",
    },
    {
        nombre: "Ricardo Morales",
        numero: "1314151617",
        correo: "ricardo.morales@example.com",
        faena: "Zaldivar",
        rol: "Administrador",
    },
    {
        nombre: "Patricia Rojas",
        numero: "1415161718",
        correo: "patricia.rojas@example.com",
        faena: "Zaldivar",
        rol: "Ingeniero",
    },
    {
        nombre: "Fernando Castillo",
        numero: "1516171819",
        correo: "fernando.castillo@example.com",
        faena: "Zaldivar",
        rol: "Mecánico",
    },
    {
        nombre: "Gabriela Soto",
        numero: "1617181920",
        correo: "gabriela.soto@example.com",
        faena: "Zaldivar",
        rol: "Técnico",
    },
    {
        nombre: "Hector Fuentes",
        numero: "1718192021",
        correo: "hector.fuentes@example.com",
        faena: "Zaldivar",
        rol: "Supervisor",
    },
    {
        nombre: "Isabel Vargas",
        numero: "1819202122",
        correo: "isabel.vargas@example.com",
        faena: "Zaldivar",
        rol: "Operador",
    },
    {
        nombre: "Oscar Reyes",
        numero: "1920212223",
        correo: "oscar.reyes@example.com",
        faena: "Zaldivar",
        rol: "Planificador",
    },
    {
        nombre: "Claudia Peña",
        numero: "2021222324",
        correo: "claudia.pena@example.com",
        faena: "Zaldivar",
        rol: "Administrador",
    },
    {
        nombre: "Diego Campos",
        numero: "2122232425",
        correo: "diego.campos@example.com",
        faena: "Zaldivar",
        rol: "Ingeniero",
    },
    {
        nombre: "Valeria Cruz",
        numero: "2223242526",
        correo: "valeria.cruz@example.com",
        faena: "Zaldivar",
        rol: "Mecánico",
    },
];